//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasOperacionais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreasOperacionais()
        {
            this.Abastecimentos = new HashSet<Abastecimentos>();
            this.Fluxos = new HashSet<Fluxos>();
            this.Fluxos1 = new HashSet<Fluxos>();
            this.Movimentacoes = new HashSet<Movimentacoes>();
            this.Paradas = new HashSet<Paradas>();
            this.Rotas = new HashSet<Rotas>();
            this.Rotas1 = new HashSet<Rotas>();
        }
    
        public System.Guid AreaOperacionalId { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public System.Guid FerroviaOperadoraId { get; set; }
        public Nullable<System.Guid> FerroviaOperadora_FerroviaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abastecimentos> Abastecimentos { get; set; }
        public virtual Ferrovias Ferrovias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fluxos> Fluxos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fluxos> Fluxos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacoes> Movimentacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paradas> Paradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rotas> Rotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rotas> Rotas1 { get; set; }
    }
}
