//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carregamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carregamentos()
        {
            this.ItensCarregamentos = new HashSet<ItensCarregamentos>();
        }
    
        public System.Guid CarregamentoId { get; set; }
        public System.Guid MercadoriaId { get; set; }
        public decimal QuantidadeCarregada { get; set; }
        public System.Guid NotaFiscalId { get; set; }
    
        public virtual Mercadorias Mercadorias { get; set; }
        public virtual NotasFiscais NotasFiscais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensCarregamentos> ItensCarregamentos { get; set; }
    }
}
