//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComposicoesVagoes
    {
        public System.Guid ComposicaoVagaoId { get; set; }
        public System.Guid ComposicaoId { get; set; }
        public System.Guid VagaoIdId { get; set; }
        public Nullable<System.Guid> Vagao_VagaoId { get; set; }
    
        public virtual Composicoes Composicoes { get; set; }
        public virtual Vagoes Vagoes { get; set; }
    }
}
