//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composicoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Composicoes()
        {
            this.ComposicoesLocomotivas = new HashSet<ComposicoesLocomotivas>();
            this.ComposicoesVagoes = new HashSet<ComposicoesVagoes>();
        }
    
        public System.Guid ComposicaoId { get; set; }
        public bool IndicadorAtivo { get; set; }
        public System.Guid TremId { get; set; }
    
        public virtual Trens Trens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposicoesLocomotivas> ComposicoesLocomotivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposicoesVagoes> ComposicoesVagoes { get; set; }
    }
}
