//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fluxos
    {
        public System.Guid FluxoId { get; set; }
        public string Codigo { get; set; }
        public System.Guid OrigemId { get; set; }
        public System.Guid DestinoId { get; set; }
        public System.Guid ClienteCorrentistaId { get; set; }
        public System.Guid MercadoriaId { get; set; }
        public System.Guid UnidadeMedidaId { get; set; }
        public Nullable<System.Guid> ClienteCorrentista_ClienteId { get; set; }
        public Nullable<System.Guid> Destino_AreaOperacionalId { get; set; }
        public Nullable<System.Guid> Origem_AreaOperacionalId { get; set; }
    
        public virtual AreasOperacionais AreasOperacionais { get; set; }
        public virtual AreasOperacionais AreasOperacionais1 { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Mercadorias Mercadorias { get; set; }
        public virtual UnidadesMedidas UnidadesMedidas { get; set; }
    }
}
