//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensCarregamentos
    {
        public System.Guid ItemCarregamentoId { get; set; }
        public System.Guid VagaoId { get; set; }
        public System.Guid CarregamentoId { get; set; }
    
        public virtual Carregamentos Carregamentos { get; set; }
        public virtual Vagoes Vagoes { get; set; }
    }
}
