//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abastecimentos> Abastecimentos { get; set; }
        public virtual DbSet<AreasOperacionais> AreasOperacionais { get; set; }
        public virtual DbSet<Carregamentos> Carregamentos { get; set; }
        public virtual DbSet<ClassesVagoes> ClassesVagoes { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Composicoes> Composicoes { get; set; }
        public virtual DbSet<ComposicoesLocomotivas> ComposicoesLocomotivas { get; set; }
        public virtual DbSet<ComposicoesVagoes> ComposicoesVagoes { get; set; }
        public virtual DbSet<Corredores> Corredores { get; set; }
        public virtual DbSet<Enderecos> Enderecos { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Ferrovias> Ferrovias { get; set; }
        public virtual DbSet<Fluxos> Fluxos { get; set; }
        public virtual DbSet<GruposFluxos> GruposFluxos { get; set; }
        public virtual DbSet<ItensCarregamentos> ItensCarregamentos { get; set; }
        public virtual DbSet<Locomotivas> Locomotivas { get; set; }
        public virtual DbSet<Mercadorias> Mercadorias { get; set; }
        public virtual DbSet<Movimentacoes> Movimentacoes { get; set; }
        public virtual DbSet<NotasFiscais> NotasFiscais { get; set; }
        public virtual DbSet<Paradas> Paradas { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Rotas> Rotas { get; set; }
        public virtual DbSet<SeriesCarregamentos> SeriesCarregamentos { get; set; }
        public virtual DbSet<SeriesLocomotivas> SeriesLocomotivas { get; set; }
        public virtual DbSet<SeriesVagoes> SeriesVagoes { get; set; }
        public virtual DbSet<Trens> Trens { get; set; }
        public virtual DbSet<UnidadesMedidas> UnidadesMedidas { get; set; }
        public virtual DbSet<Vagoes> Vagoes { get; set; }
    }
}
