//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public System.Guid PedidoId { get; set; }
        public string Codigo { get; set; }
        public System.Guid GrupoFluxoId { get; set; }
        public System.DateTime DataPedido { get; set; }
        public int QuantidadeVagoes { get; set; }
    
        public virtual GruposFluxos GruposFluxos { get; set; }
    }
}
