//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.Infra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vagoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vagoes()
        {
            this.ComposicoesVagoes = new HashSet<ComposicoesVagoes>();
            this.ItensCarregamentos = new HashSet<ItensCarregamentos>();
        }
    
        public System.Guid VagaoId { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool Ativo { get; set; }
        public string Codigo { get; set; }
        public string Bitola { get; set; }
        public int QuantidadeEixos { get; set; }
        public double CapacidadeNominal { get; set; }
        public double Comprimento { get; set; }
        public double Largura { get; set; }
        public double Altura { get; set; }
        public double ComprimentoUtil { get; set; }
        public double LarguraUtil { get; set; }
        public double VolumeMedio { get; set; }
        public System.DateTime DataFabricacao { get; set; }
        public double Tara { get; set; }
        public System.Guid FerroviaOPeradoraId { get; set; }
        public System.Guid SerieVagaoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposicoesVagoes> ComposicoesVagoes { get; set; }
        public virtual Ferrovias Ferrovias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensCarregamentos> ItensCarregamentos { get; set; }
        public virtual SeriesVagoes SeriesVagoes { get; set; }
    }
}
